### ISSUE TITLE
JIRA Cloud support

### ISSUE THREAD

**Issue by ewilson90** [MeetMe/jira-gerrit-plugin#32]
Is it possible for this plug-in to support Jira cloud installations?

**Comment by jhansche** [comment]
Please see #17

**Comment by jhansche** [comment]
Jira Cloud requires a completely separate implementation, as they do not allow in-process plugins to be installed into Jira Cloud installations.  Instead, panels are created as a series of webhooks and REST APIs in order to customize the interface.

Given that, it will not be possible or feasible to introduce that support into this plugin. However, it may be possible to create a web service that handles communication between the Jira Cloud installation and your Gerrit installation, in order to make similar panels for Jira Cloud. That is not something that this plugin will be able to do, and we have no plans to create a public web service that can do this marshalling for you.

That said, it may be possible to create a Gerrit plugin that acts as the web hook that can be installed into Jira Cloud -- assuming your Gerrit installation is accessible to the Jira Cloud.
