### ISSUE TITLE
Show closed/merged reviews as well as open reviews

### ISSUE THREAD

**Issue by johntoenail** [MeetMe/jira-gerrit-plugin#34]
As a user using the jira-gerrit-plugin to provide a connection between conducted reviews for a given ticket I would like to 
- have a history function
-- such that my ticket contains all tickets for the relevant search, i.e. open, closed and merged, closed and abandoned reviews
- a way to differentiate between open and closed reviews in the tickets, e.g. by means of a badge or a different icon.

Currently only open reviews are shown within the tickets.

I could not find any documentation that would identify this as a misconfiguration. 
The Gerrit query used returns open and closed reviews, I would expect this to be reflected in the JIRA ticket as well.

**Comment by jhansche** [comment]
There was a bug in the plugin when running on certain version of JIRA 7.x, where the drop-down menu of filter options on the main issue web panel was not appearing.

That has been fixed in version 3.1, just released to the marketplace: https://marketplace.atlassian.com/plugins/com.meetme.plugins.jira.gerrit-plugin/versions#b57

The original intent of that drop-down menu was to give you the option to choose between:

* Only this issue, or this issue and all subtask issues
* Show reviews that match only open JIRA issues, or open & closed
* Show reviews that are open, or include closed (abandoned & merged) reviews

Somewhere in the JIRA 7.x line, that drop-down menu stopped appearing, due to a deprecation of one of the plugin components (simple link factory -> web item provider).  The 3.1 plugin release fixes that by converting to the new WebItemProvider.

With that fix, you should now be able to filter what appears in the web panel, so that you can see both open and closed reviews that match the issue.

**Comment by lenucksi** [comment]
Just verified it, works fine now. Thanks! 👍
