### ISSUE TITLE
botched rendering of gerrit side panel

### ISSUE THREAD

**Issue by ossilator** [MeetMe/jira-gerrit-plugin#45]
see this screenshot:
![spectacle tt7094](https://cloud.githubusercontent.com/assets/812380/23606339/923afe70-0260-11e7-924d-6d9dbc52483b.png)

also, on the "-1 g" line, maaaaaaany pixels to the right, appears the word "Gerrit".

pasted from the downstream report https://bugreports.qt.io/browse/QTJIRA-306:

When you open an issue with gerrit review pinned (e.g. https://bugreports.qt.io/browse/QTBUG-59298) you can see, that some stuff that Gerrit Plugin is rendering is offset by a gian number of pixels.

Look at the horizontal scrollbar of your browser. Word "Gerrit" will be rendered in some insane length to the right.

It seems that there may be some bug in CSS. This span element that contains words "Gerrit Reviews" has "text-indent: 9999px"

**Comment by jhansche** [comment]
That looks like the CSS is missing an {{overflow: hidden}} CSS rule, for that checkmark.  It appears off to the right because of a {{text-indent: 9999px}} rule.  That is there so that screen-readers can see the text, but modern browsers should render only the checkmark.

I don't know how/when that {{overflow:hidden}} rule got removed, but that would be the fix.

**Comment by mcpaddy** [comment]
We are also hitting this problem. The fix suggested in the pull request resolves the issue for us.
