### ISSUE TITLE
Could only the first few characters up the first ":" needs to be considered as affected in JIRA

### ISSUE THREAD

**Issue by Robin0321** [MeetMe/jira-gerrit-plugin#49]
Hi team,

We have faced a problem that , we use "message:%s" as Optionally change the Gerrit search query patterns in jira.But , when our customer commit a message says 
![gerrit review commit message](https://cloud.githubusercontent.com/assets/28126954/25512498/c7003084-2c00-11e7-87b5-d892cd460360.png)
The plugin shows this info below the DDE-1 issue,However , the commit message only contains "DDE 1.2" which is different from "DDE-1". Our customer think it is a bug.
Could you please tell us if this plugin can only use the first characters up the first ":".Such as only  "EPC-15329 "  matters for mapping?

BR
SDC Jira Support Team

**Comment by Robin0321** [comment]
Can someone follow this ticket ?

**Comment by jhansche** [comment]
This would probably need to be a new feature for the parser.  I don't see why it would be interpreting `DDE 1.2:` as if it were `DDE-1`, because it's missing the `-` that is expected in Jira issue ids.

Unfortunately it looks like this is an artifact of the "Full Text" (secondary index -- e.g. Lucene) searching in Gerrit.  If you type `message:DDE-1` into your Gerrit search bar, it will return the commit for `EPC-15329` because it doesn't do exact text matching, but instead converts the search criteria to something that can be searched with full-text queries.

I don't know of any way to relax that searching, as it is something done automatically by Gerrit. I don't see any search predicate or operator that enforces an "exact match" like that, as the default search for `message:` is to use the lucene index, which performs full-text searches (that is, it looks for bare words, not symbols).

The only way I can think for you to resolve this would be to integrate the trackingIds config, and use the `tr:%s` predicate instead in your Jira configuration for the Gerrit plugin.  The `tr:` predicate should provide exact matching, because it has to extract the bug id into a separate table.  See system configuration for this option: https://gerrit-documentation.storage.googleapis.com/Documentation/2.14.2/config-gerrit.html#trackingid

**Comment by felipecrs** [comment]
I have the same issue. In our case, we are integrating this plugin with a 5 years old convention of commit message such as:

```text
Trackind-Id: US:JIRA-1234
```

Because of the leading colon, the issue does not get properly recognized. It works if we enclose the ID with square brackets.

**Comment by jhansche** [comment]
As mentioned in the comment above, this isn't something that the plugin is doing. This is how Gerrit search works. The plugin does not itself scan every commit and look for Jira ids - it asks Gerrit to search for the issue id you are viewing. If Gerrit doesn't have a search predicate that works for you, then there's not much more the plugin can do for you.

I would suggest you spend some time with trial-and-error search predicates by typing some search queries into the search box on Gerrit. When you find something that works for your commit message format, then you can update the plugin configuration to use that. For example, you might try searching for `message:US:JIRA-1234` and see if that allows it to find your commits. If so, then you can update the configuration to include the `US:` prefix. If there are other possible prefixes, then you can also use an OR search operator, and replace `%s` with `%1$s` (%s just means use the next replacement token; but %1$s means use the _first_ replacement token, and so on). For example, if you have `US`, `GB`, `DE` prefixes, you could try: `message:US:%1$s OR message:GB:%1$s OR message:DE:%1$s`, and see if that works.

You can test it first in the Gerrit search box, before saving it in the Jira plugin configuration.
