### ISSUE TITLE
Way to identify JIRA tickets that have an associated gerrit review

### ISSUE THREAD

**Issue by vimvik** [MeetMe/jira-gerrit-plugin#60]
Is there an easy way to identify jira tickets that are already being worked on in Gerrit? And tickets for which there are already submitted commits?

**Comment by jhansche** [comment]
This is not possible, because Jira does not "sync" all known issue references. It only queries gerrit at the time of viewing an issue, thus showing only reviews relevant to that issue only.

If you just want to know what tickets have current open reviews, the right tool for that is gerrit itself: you can search for all open changes, and see everything right in Gerrit's dashboard
