### ISSUE TITLE
Always 'No reviews matched the request'

### ISSUE THREAD

**Issue by coderfengyun** [MeetMe/jira-gerrit-plugin#61]
I install it in jira market place, and config it as the documentation says. But when i look at the issue, it always say "No reviews matched the request. Check your Options in the drop-down menu of this sections header.";  And when i manage the plugin, the "Test Config" button give no response.

**Comment by coderfengyun** [comment]
jira version: v6.4
Gerrit Code Review for Jira: v. 2.3.1

**Comment by jhansche** [comment]
The latest versions of the plugin (as of 3.0 and newer) do not support JIRA 6 or older.

What version of Gerrit do you use?  Also, check the search query string in Gerrit, and make sure that a search in Gerrit returns the commits that you're expecting. If not, then the plugin cannot possibly include that data, because that search is exactly how the plugin works.
