### ISSUE TITLE
Jira-Cloud availability

### ISSUE THREAD

**Issue by denispilat** [MeetMe/jira-gerrit-plugin#87]
Hello

Do you know when the plugin will be supported by the Cloud version of JIRA ?

Thanks
Denis

**Comment by jhansche** [comment]
This plugin cannot work with Jira Cloud, because the plugin architecture is completely different.
My company will be looking to switch to Cloud sometime this year, so the plugin will have to be rewritten for Cloud. When that happens it won't be associated with this plugin, which is compatible with Jira Server only.
