### ISSUE TITLE
delete the Gerrit code reviews from Jira

### ISSUE THREAD

**Issue by a412710** [MeetMe/jira-gerrit-plugin#89]
There is not an option to delete the Gerrit code reviews from the Jira project I will delete that because it was mapped with the wrong Jira. Can you help me, please?

<img width="701" alt="Capture" src="https://user-images.githubusercontent.com/105638642/168581867-7f885cfa-660e-4be9-8575-4cb8ca955340.PNG">

**Comment by a412710** [comment]
Hi Team,

Can we have a quick update on this?
BR
Mostafa

**Comment by jhansche** [comment]
I don't think I understand. If you deleted the project then there's nothing for the plugin to show associated with that project. Deleting Gerrit reviews from Jira is not going to be supported because that requires admin privileges in Gerrit, and goes against the principles of git that you not rewrite history. 

The plugin only does a search of Gerrit using the query you configured in the plugin config screen. If a change matches that, it will appear, otherwise it won't. If you rename a Jira project, or move an issue to another project, it will also try to find changes for the older issue id(s).
