### ISSUE TITLE
Looking for a JQL and CSV export support

### ISSUE THREAD

**Issue by baswath** [MeetMe/jira-gerrit-plugin#95]
I'm looking for a JQL that can filter all issues containing at least one gerrit review ID and export all review IDs including JIRA ID to a CSV file from JIRA export. Is the functionality I'm looking for available, and if so, please provide the necessary instructions. I require a JIRA specific resolution.

**Comment by jhansche** [comment]
Unfortunately that's not how the plugin works. The plugin queries Gerrit only when viewing a Jira issue, to find Gerrit changes that mention the issue you're viewing. It does not keep a record (beyond a local in-memory cache) of issues that have open changes.

If you enable tracking_ids in Gerrit, it will store matching tracking ids in its own database, that's one option.

Otherwise a more common way to achieve this would be to query Gerrit for open changes, and then use a regular expression or some other common standards you've agreed on in your organization to extract what look like Jira issue ids from the commit messages of the open changes.

This plugin does not work like the DVCS system in Jira (how the GitHub plugin works for example), because the DVCS system is not open and not documented, so contributing to the development panel is not something that atlassian allows (at least not officially).
